In [2]:

import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

import seaborn as sns

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/Zipcoder/DataEngineering.Labs.Libraries/master/\
Pandas%20-%20Part%201%20(importing%20data%2C%20summary%20stats)/Combined%20Wine%20Data.csv?\
token=ALOLXOJ73RI2TJV7EOL3DHK6HNRPQ")

In [4]:
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [5]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [8]:
data['sweet_or_not'] = np.where(data['residual sugar'] >= data['residual sugar'].mean(), True, False)

In [9]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color,sweet_or_not
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,False
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red,False
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red,False
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red,False
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,False

In [10]:
quality = 6
sweet = True
alcohol = data.alcohol.quantile(0.75)
color = 'red'

In [11]:
condition = np.logical_and(data['quality'] >= quality,data['sweet_or_not'] == sweet)
condition = np.logical_and(condition, data['alcohol'] > alcohol)
condition = np.logical_and(condition, data['color'] > color)

In [12]:
condition.value_counts()

False    6212
True      285
dtype: int64

In [13]:
data['i_like_it'] = condition

In [14]:
the_one_i_like = data[data['i_like_it'] == True]

In [15]:
the_one_i_like

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color,sweet_or_not,i_like_it
1665,6.4,0.26,0.24,6.4,0.040,27.0,124.0,0.99030,3.22,0.49,12.60,7,white,True,True
1749,7.9,0.22,0.38,8.0,0.043,46.0,152.0,0.99340,3.12,0.32,11.50,7,white,True,True
1774,6.9,0.23,0.40,7.5,0.040,50.0,151.0,0.99270,3.11,0.27,11.40,6,white,True,True
1791,6.8,0.28,0.36,8.0,0.045,28.0,123.0,0.99280,3.02,0.37,11.40,6,white,True,True
1802,6.8,0.26,0.34,13.9,0.034,39.0,134.0,0.99490,3.33,0.53,12.00,6,white,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6436,6.5,0.28,0.38,7.8,0.031,54.0,216.0,0.99154,3.03,0.42,13.10,6,white,True,True
6439,6.8,0.34,0.36,8.9,0.029,44.0,128.0,0.99318,3.28,0.35,11.95,7,white,True,True
6456,7.5,0.38,0.33,9.2,0.043,19.0,116.0,0.99444,3.08,0.42,11.40,6,white,True,True
6469,6.1,0.32,0.28,6.6,0.021,29.0,132.0,0.99188,3.15,0.36,11.45,7,white,True,True
6485,6.2,0.21,0.28,5.7,0.028,45.0,121.0,0.99168,3.21,1.08,12.15,7,white,True,True

In [17]:
the_one_i_like.to_csv('my favourite wines1.csv')