In [1]:
import pandas as pd 

%matplotlib inline
import matplotlib.pyplot as plt

import seaborn as sns

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/Zipcoder/DataEngineering.Labs.Libraries/master/Pandas%20-%20Part%201%20(importing%20data%2C%20summary%20stats)/\
Combined%20Wine%20Data.csv?token=ALOLXOLFRIDBG2N4OHH2NIK6HNDGY")

In [3]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [4]:
columns = data.columns.to_list()

In [5]:
columns

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality',
 'color']

In [6]:
columns.sort()

In [7]:
columns

['alcohol',
 'chlorides',
 'citric acid',
 'color',
 'density',
 'fixed acidity',
 'free sulfur dioxide',
 'pH',
 'quality',
 'residual sugar',
 'sulphates',
 'total sulfur dioxide',
 'volatile acidity']

In [8]:
columns.insert(0,columns.pop(columns.index('color')))

In [9]:
columns

['color',
 'alcohol',
 'chlorides',
 'citric acid',
 'density',
 'fixed acidity',
 'free sulfur dioxide',
 'pH',
 'quality',
 'residual sugar',
 'sulphates',
 'total sulfur dioxide',
 'volatile acidity']

In [10]:
rearranged_data = data[columns]

In [11]:
rearranged_data.head()

,color,alcohol,chlorides,citric acid,density,fixed acidity,free sulfur dioxide,pH,quality,residual sugar,sulphates,total sulfur dioxide,volatile acidity
0,red,9.4,0.076,0.00,0.9978,7.4,11.0,3.51,5,1.9,0.56,34.0,0.70
1,red,9.8,0.098,0.00,0.9968,7.8,25.0,3.20,5,2.6,0.68,67.0,0.88
2,red,9.8,0.092,0.04,0.9970,7.8,15.0,3.26,5,2.3,0.65,54.0,0.76
3,red,9.8,0.075,0.56,0.9980,11.2,17.0,3.16,6,1.9,0.58,60.0,0.28
4,red,9.4,0.076,0.00,0.9978,7.4,11.0,3.51,5,1.9,0.56,34.0,0.70

In [13]:
data[columns].head()

,color,alcohol,chlorides,citric acid,density,fixed acidity,free sulfur dioxide,pH,quality,residual sugar,sulphates,total sulfur dioxide,volatile acidity
0,red,9.4,0.076,0.00,0.9978,7.4,11.0,3.51,5,1.9,0.56,34.0,0.70
1,red,9.8,0.098,0.00,0.9968,7.8,25.0,3.20,5,2.6,0.68,67.0,0.88
2,red,9.8,0.092,0.04,0.9970,7.8,15.0,3.26,5,2.3,0.65,54.0,0.76
3,red,9.8,0.075,0.56,0.9980,11.2,17.0,3.16,6,1.9,0.58,60.0,0.28
4,red,9.4,0.076,0.00,0.9978,7.4,11.0,3.51,5,1.9,0.56,34.0,0.70

In [14]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [15]:
rearranged_data['residual sugar'].mean()

5.443235339387409

In [25]:
high_sugar_winess = rearranged_data[rearranged_data['residual sugar'] > rearranged_data['residual sugar'].mean()]

In [26]:
high_sugar_winess

,color,alcohol,chlorides,citric acid,density,fixed acidity,free sulfur dioxide,pH,quality,residual sugar,sulphates,total sulfur dioxide,volatile acidity
9,red,10.50,0.071,0.36,0.99780,7.5,17.0,3.35,5,6.10,0.80,102.0,0.500
11,red,10.50,0.071,0.36,0.99780,7.5,17.0,3.35,5,6.10,0.80,102.0,0.500
33,red,9.40,0.073,0.12,0.99930,6.9,40.0,3.45,6,10.70,0.52,83.0,0.605
35,red,9.60,0.086,0.00,0.99860,7.8,5.0,3.40,6,5.50,0.55,18.0,0.645
39,red,10.50,0.074,0.36,0.99780,7.3,12.0,3.33,5,5.90,0.83,87.0,0.450
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6483,white,9.60,0.048,0.38,0.99492,6.5,68.0,3.14,5,8.30,0.50,174.0,0.330
6484,white,9.55,0.046,0.40,0.99494,6.6,68.0,3.15,6,8.10,0.50,170.0,0.340
6485,white,12.15,0.028,0.28,0.99168,6.2,45.0,3.21,7,5.70,1.08,121.0,0.210
6488,white,9.40,0.030,0.27,0.99540,4.9,34.0,3.07,6,11.75,0.50,118.0,0.235
6493,white,9.60,0.047,0.36,0.99490,6.6,57.0,3.15,5,8.00,0.46,168.0,0.320

In [27]:
high_sugar_winess.color.value_counts()

white    2383
red        74
Name: color, dtype: int64

In [28]:
high_sugar_wine = high_sugar_winess[high_sugar_winess.color != 'white']

In [29]:
high_sugar_wine

,color,alcohol,chlorides,citric acid,density,fixed acidity,free sulfur dioxide,pH,quality,residual sugar,sulphates,total sulfur dioxide,volatile acidity
9,red,10.5,0.071,0.36,0.99780,7.5,17.0,3.35,5,6.1,0.80,102.0,0.500
11,red,10.5,0.071,0.36,0.99780,7.5,17.0,3.35,5,6.1,0.80,102.0,0.500
33,red,9.4,0.073,0.12,0.99930,6.9,40.0,3.45,6,10.7,0.52,83.0,0.605
35,red,9.6,0.086,0.00,0.99860,7.8,5.0,3.40,6,5.5,0.55,18.0,0.645
39,red,10.5,0.074,0.36,0.99780,7.3,12.0,3.33,5,5.9,0.83,87.0,0.450
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,red,8.8,0.205,0.50,1.00242,9.9,48.0,3.16,5,13.8,0.75,82.0,0.500
1478,red,10.2,0.082,0.05,0.99808,7.1,3.0,3.40,3,5.7,0.52,14.0,0.875
1558,red,9.5,0.235,0.33,0.99787,6.9,66.0,3.22,5,6.7,0.56,115.0,0.630
1574,red,10.5,0.074,0.78,0.99677,5.6,23.0,3.39,6,13.9,0.48,92.0,0.310
1589,red,9.2,0.073,0.20,0.99770,6.6,29.0,3.29,5,7.8,0.54,79.0,0.725

In [30]:
high_sugar_wine.head()

,color,alcohol,chlorides,citric acid,density,fixed acidity,free sulfur dioxide,pH,quality,residual sugar,sulphates,total sulfur dioxide,volatile acidity
9,red,10.5,0.071,0.36,0.9978,7.5,17.0,3.35,5,6.1,0.80,102.0,0.500
11,red,10.5,0.071,0.36,0.9978,7.5,17.0,3.35,5,6.1,0.80,102.0,0.500
33,red,9.4,0.073,0.12,0.9993,6.9,40.0,3.45,6,10.7,0.52,83.0,0.605
35,red,9.6,0.086,0.00,0.9986,7.8,5.0,3.40,6,5.5,0.55,18.0,0.645
39,red,10.5,0.074,0.36,0.9978,7.3,12.0,3.33,5,5.9,0.83,87.0,0.450

In [31]:
high_sugar_wine.sort_values(by='residual sugar', ascending=False)

,color,alcohol,chlorides,citric acid,density,fixed acidity,free sulfur dioxide,pH,quality,residual sugar,sulphates,total sulfur dioxide,volatile acidity
480,red,9.2,0.069,0.39,1.00260,10.6,6.0,3.12,5,15.5,0.66,23.0,0.280
1435,red,9.0,0.214,0.37,1.00369,10.2,55.0,3.18,6,15.4,0.77,95.0,0.540
1434,red,9.0,0.214,0.37,1.00369,10.2,55.0,3.18,6,15.4,0.77,95.0,0.540
1574,red,10.5,0.074,0.78,0.99677,5.6,23.0,3.39,6,13.9,0.48,92.0,0.310
1476,red,8.8,0.205,0.50,1.00242,9.9,48.0,3.16,5,13.8,0.75,82.0,0.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,red,10.5,0.071,0.42,0.99730,7.1,28.0,3.42,5,5.5,0.71,128.0,0.430
154,red,10.5,0.070,0.42,0.99730,7.1,29.0,3.42,5,5.5,0.72,129.0,0.430
1133,red,11.2,0.089,0.07,0.99684,7.2,10.0,3.37,7,5.5,0.68,18.0,0.480
35,red,9.6,0.086,0.00,0.99860,7.8,5.0,3.40,6,5.5,0.55,18.0,0.645
1094,red,10.8,0.117,0.09,0.99655,6.6,9.0,3.35,6,5.5,0.49,17.0,0.725